-- ─────────────────────────────────────────────────────────────
--  DrainGuard Mesh — Supabase Cloud PostgreSQL Database Schema
--  Run this script in your Supabase Project -> SQL Editor
-- ─────────────────────────────────────────────────────────────

-- 1. Users Table (Municipal Operators & Engineers)
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  full_name TEXT,
  role TEXT DEFAULT 'operator',
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()),
  last_login_at TIMESTAMPTZ
);

-- 2. Login & Registration Audit Logs Table
CREATE TABLE IF NOT EXISTS public.login_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  username TEXT,
  email TEXT,
  role TEXT,
  status TEXT NOT NULL,
  ip_address TEXT,
  user_agent TEXT,
  timestamp TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 3. Sensor Telemetry Table (ESP32 & IoT Readings)
CREATE TABLE IF NOT EXISTS public.sensor_telemetry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sensor_id TEXT NOT NULL,
  flow_rate DOUBLE PRECISION DEFAULT 1.0,
  water_level DOUBLE PRECISION DEFAULT 0.3,
  velocity DOUBLE PRECISION DEFAULT 1.2,
  battery_level DOUBLE PRECISION DEFAULT 90,
  status TEXT DEFAULT 'normal',
  source TEXT DEFAULT 'esp32_hardware',
  timestamp TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 4. Flood Simulation & Real Incidents Table
CREATE TABLE IF NOT EXISTS public.flood_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status TEXT NOT NULL, -- 'active', 'resolved'
  triggered_by TEXT NOT NULL, -- 'manual', 'esp32_hardware', 'sensor'
  sensor_id TEXT,
  started_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()),
  ended_at TIMESTAMPTZ
);

-- 5. Drainage Alerts Table
CREATE TABLE IF NOT EXISTS public.alerts (
  id TEXT PRIMARY KEY,
  severity TEXT NOT NULL, -- 'critical', 'warning', 'info'
  pipe_id TEXT,
  segment_label TEXT,
  location TEXT,
  message TEXT,
  confidence DOUBLE PRECISION DEFAULT 95.0,
  resolved INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()),
  resolved_at TIMESTAMPTZ
);

-- 6. Maintenance Work Orders Table
CREATE TABLE IF NOT EXISTS public.work_orders (
  id TEXT PRIMARY KEY,
  alert_id TEXT,
  pipe_id TEXT,
  team TEXT,
  priority TEXT DEFAULT 'P1',
  access_point TEXT,
  status TEXT DEFAULT 'assigned',
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()),
  completed_at TIMESTAMPTZ,
  verified_at TIMESTAMPTZ
);

-- Enable Row Level Security (RLS) & Public Read/Write Policies (for App Backend)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.login_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sensor_telemetry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.flood_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read/write users" ON public.users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write login_logs" ON public.login_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write telemetry" ON public.sensor_telemetry FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write flood_events" ON public.flood_events FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write alerts" ON public.alerts FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write work_orders" ON public.work_orders FOR ALL USING (true) WITH CHECK (true);
